pipeline {
    agent any
    environment {
        micro_frontend_dir = 'app'
    }

    stages {
        stage ('Check Yarn Availability') {
            steps {
                dir(micro_frontend_dir) {
                    sh "yarn --version"
                }
            }
        }

         stage ('Install dependencies') {
            steps {
                dir(micro_frontend_dir) {
                    sh "yarn  install"
                }
            }
        }

         stage ('Run tests') {
            steps {
                dir(micro_frontend_dir) {
                    sh "yarn test"
                }
            }
        }

         stage ('Build package') {
            steps {
                dir(micro_frontend_dir) {
                    sh "yarn build"
                }
            }
        }

         /*stage ('Send package to aws') {
            steps {
                dir(micro_frontend_dir) {
                    sh "aws s3 sync "
                }
            }
        }*/
    }
}