pipeline {
    def micro_frontend_dir = 'appshell'
    agent any

    stages {
        stage ('Check Yarn Availability') {
            steps {
                sh "pwd"
                dir('${env.WORKSPACE}/'+micro_frontend_dir) {
                    sh "pwd"
                    sh "yarn --version"
                }
            }
        }

         stage ('Install dependencies') {
            steps {
                sh "pwd"
                dir('${env.WORKSPACE}/'+micro_frontend_dir) {
                    sh "pwd"
                    sh "yarn  install"
                }
            }
        }

         stage ('Run tests') {
            steps {
                sh "pwd"
                dir('${env.WORKSPACE}/'+micro_frontend_dir) {
                    sh "pwd"
                    sh "yarn test"
                }
            }
        }

         stage ('Build package') {
            steps {
                sh "pwd"
                dir('${env.WORKSPACE}/'+micro_frontend_dir) {
                    sh "pwd"
                    sh "yarn build"
                }
            }
        }

         /*stage ('Send package to aws') {
            steps {
                dir(micro_frontend_dir) {
                    sh "aws s3 sync "
                }
            }
        }*/
    }
}